### PR TITLE
Properly X.509 encode RSA signatures imported from raw bytes

### LINKED ISSUE #195: RSA Key Pair Generation on JVM - CertificateException: Invalid Padding Bits
First of all great job!
I’m attempting to generate an RSA key pair with the following configuration:
```
rsa {
    paddings = setOf(RSAPadding.PKCS1)
    digests = setOf(Digest.SHA256)
    publicExponent = SigningKeyConfiguration.RSAConfiguration.F4
}
```
However, I encounter this error specifically on the JVM target (it works fine on iOS and Android):
```
java.security.cert.CertificateException: Unable to initialize, java.io.IOException: Invalid number of padding bits
	at java.base/sun.security.x509.X509CertImpl.<init>(Unknown Source)
	at java.base/sun.security.provider.X509Factory.cachedGetX509Cert(Unknown Source)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(Unknown Source)
	at java.base/java.security.cert.CertificateFactory.generateCertificate(Unknown Source)
	at at.asitplus.signum.indispensable.JcaExtensionsKt.toJcaCertificate(JcaExtensions.kt:218)
```
It appears to be an issue with converting to JcaCertificate. Any insights on resolving this for JVM?
Thanks

### PR DESCRIPTION
**Pull request by iaik-jheher**
There was confusion about whether the bytes stored in the signature object were already ASN.1 BitString encoded or not. Closes #195.

### CODE REVIEW

**Comment by iaik-jheher** [comment]
@JesusMcCloud add a regression test to the branch please

**Comment by iaik-jheher** [comment]
[This](https://github.com/a-sit-plus/signum/blob/main/indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/CryptoPublicKey.kt#L255) is also suspicious to me, so please also add a regression test for the parallel publickey encoding.

**Comment by JesusMcCloud** [comment]
> [This](https://github.com/a-sit-plus/signum/blob/main/indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/CryptoPublicKey.kt#L255) is also suspicious to me, so please also add a regression test for the parallel publickey encoding.

Yes, this smells funky

**Comment by JesusMcCloud** [comment]
ping me, once this one is ready

**Review by JesusMcCloud — APPROVED** [review]
Pending all Tests are green

**Pull request merged**
