### PR TITLE
Refactor decoding numbers from byte arrays

### LINKED ISSUE #123: Refactor: Extract extension function
Try to make

```kotlin
fun Long.Companion.fromTwosComplementByteArray(it: ByteArray) = when (it.size) {
    8 -> (it[0].toLong() shl 56) or (it[1].toUByte().toLong() shl 48) or (it[2].toUByte().toLong() shl 40) or
            (it[3].toUByte().toLong() shl 32) or (it[4].toUByte().toLong() shl 24) or
            (it[5].toUByte().toLong() shl 16) or (it[6].toUByte().toLong() shl 8) or (it[7].toUByte().toLong())
    7 -> (it[0].toLong() shl 48) or (it[1].toUByte().toLong() shl 40) or (it[2].toUByte().toLong() shl 32) or
            (it[3].toUByte().toLong() shl 24) or (it[4].toUByte().toLong() shl 16) or
            (it[5].toUByte().toLong() shl 8) or (it[6].toUByte().toLong())
    6 -> (it[0].toLong() shl 40) or (it[1].toUByte().toLong() shl 32) or (it[2].toUByte().toLong() shl 24) or
            (it[3].toUByte().toLong() shl 16) or (it[4].toUByte().toLong() shl 8) or (it[5].toUByte().toLong())
    5 -> (it[0].toLong() shl 32) or (it[1].toUByte().toLong() shl 24) or (it[2].toUByte().toLong() shl 16) or
            (it[3].toUByte().toLong() shl 8) or (it[4].toUByte().toLong())
    4 -> (it[0].toLong() shl 24) or (it[1].toUByte().toLong() shl 16) or (it[2].toUByte().toLong() shl 8) or
            (it[3].toUByte().toLong())
    3 -> (it[0].toLong() shl 16) or (it[1].toUByte().toLong() shl 8) or (it[2].toUByte().toLong())
    2 -> (it[0].toLong() shl 8) or (it[1].toUByte().toLong() shl 0)
    1 -> (it[0].toLong())
    else -> throw IllegalArgumentException("Input with size $it is out of bounds for Long")
}
```

in `Asn1Encoding.kt` more readable by extracting extension functions.

### PR DESCRIPTION
**Pull request by nodh**
Fixes #123

### CODE REVIEW

**Comment by iaik-jheher** [comment]
ping me once #117 is merged, since the diff should be more manageable to review then

**Comment by nodh** [comment]
> ping me once #117 is merged, since the diff should be more manageable to review then

Rebased now

**Comment by iaik-jheher** [comment]
these were intentionally unrolled for performance (per @JesusMcCloud)

**Comment by JesusMcCloud** [comment]
and i have the numbers to back it up! just look at the runtimes for iOS:

the number decoding is only a fraction of the total test time and still there is a significant difference: https://github.com/a-sit-plus/signum/actions/runs/10878922567 vs https://github.com/a-sit-plus/signum/actions/runs/10878578188

**Comment by JesusMcCloud** [comment]
once and if we switch to koltinx.io (See #120), we can revisit this. Since I now tagged it, i think we can close this PR for now?!

**Pull request closed without merging**
